### ISSUE TITLE
Provider not working on strapi endpoints

### ISSUE THREAD

**Issue by Rollbusch** [red-made/strapi-provider-email-brevo#2]
I'm opening this issue because i wanna know if it is a plugin issue

Currently I’m using the lib strapi-provider-email-brevo as email provider. When i use the “send test email” option on configuration tab, i receive the email without any problems. But its not the same when i try to use forgot-password API.

Send Test Email option showing its using the right provider
https://i.imgur.com/yYDwZtx.png

Strapi email received without any problems
https://i.imgur.com/OgRIy9l.png

My strapi **plugins.js** file
https://i.imgur.com/mFZdD7T.png

I tried to debug the lib, writing some console.log anywhere in the code and when I use the test button on strapi it shows me the logs but when I try to do some request using api/auth/forgot-password seems like it did not use the provider lib (https://i.imgur.com/egQzJKi.png). And yeah, the permissions are currently true (https://i.imgur.com/QaVGP5N.png). I also found an email api with “send” endpoint, I also tried to set it to true but it also didnt made any changes (https://i.imgur.com/z9KLCAb.png)
Request using thunder client on Vscode
https://i.imgur.com/T8efYHG.png

 System Information
 - Strapi Version: 4.13.7
 - Operating System: Ubuntu
 - Database: Sqlite3
 - Node Version: 18.18.1
 - NPM Version: 9.8.1

**Comment by red-made** [comment]
Sorry for the late response, tested right now, I received the forgotten password email without any problems.
